apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  labels:
    name: locust-worker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: 27061998/locust:guestbook
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER_URL
              value: locust-master
            - name: TARGET_HOST
              value: http://frontend-internal
